<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email_vt du vu vv vw vx vy vz wa wb wc wd we wf wg cf aw wh</name>
   <tag></tag>
   <elementGuidId>2e3e9ec4-5f56-4d45-8d1d-c2e03fa6ba6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='sachhongo@mail.com']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.vt.du.vu.vv.vw.vx.vy.vz.wa.wb.wc.wd.we.wf.wg.cf.aw.wh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vt du vu vv vw vx vy vz wa wb wc wd we wf wg cf aw wh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>sachhongo@mail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;susi-modal-background&quot;)/div[@class=&quot;ma hx r um v aq ev un uo hg up&quot;]/div[@class=&quot;uq ur v ap ch w fq cf us hp hg&quot;]/div[@class=&quot;jn u&quot;]/div[@class=&quot;v ap ch&quot;]/div[@class=&quot;vs qw u&quot;]/div[1]/div[@class=&quot;wi wd v ap ch cf&quot;]/div[@class=&quot;iw&quot;]/div[@class=&quot;ky u&quot;]/h4[@class=&quot;lo b bp av ds&quot;]/input[@class=&quot;vt du vu vv vw vx vy vz wa wb wc wd we wf wg cf aw wh&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='sachhongo@mail.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='susi-modal-background']/div/div/div[3]/div/div[2]/div/div/div[2]/div/h4/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
